name: "quix-manager"
version: "0.1.0"
usage: "helm quix-manager update --release-name quixplatform-manager --repo quixcontainerregistry.azurecr.io/helm/quixplatform-manager:1.5.4"
description: |-
  A helm plugin to install quix.
ignoreFlags: false
useTunnel: true
command: "python $HELM_PLUGIN_DIR/quix-install-command.py"